# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

import pandas as pd
df = pd.read_excel('TestFile.xlsx', index_col=0)
df.loc[1, 1] = "Vishwa"

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1125, 624)
        self.Button = QtWidgets.QPushButton(parent=Dialog)
        self.Button.setGeometry(QtCore.QRect(20, 50, 93, 28))
        self.Button.setObjectName("Button")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(150, 50, 301, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.tBLog = QtWidgets.QTextBrowser(parent=Dialog)
        self.tBLog.setGeometry(QtCore.QRect(20, 90, 431, 192))
        self.tBLog.setObjectName("tBLog")
        self.graphicsView = QtWidgets.QGraphicsView(parent=Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(470, 90, 641, 192))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Button.setText(_translate("Dialog", "Switch"))
        self.Button.clicked.connect(self.printValue)

    def printValue(self):
        self.lineEdit.setText("Hello")
        print(self.lineEdit.text())
        self.tBLog.append(df.loc[1].Name+"," + str(df.loc[1].Password))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QWidget()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
